// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VBlock_adder_total.h for the primary calling header

#ifndef VERILATED_VBLOCK_ADDER_TOTAL___024ROOT_H_
#define VERILATED_VBLOCK_ADDER_TOTAL___024ROOT_H_  // guard

#include "verilated.h"


class VBlock_adder_total__Syms;

class alignas(VL_CACHE_LINE_BYTES) VBlock_adder_total___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellout__FA0__o_s;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA1__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA2__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA3__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA4__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA5__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA6__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA7__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA8__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA9__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA10__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA11__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA12__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA13__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA14__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA15__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA16__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA17__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA18__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA19__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA20__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA21__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA22__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA23__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA24__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA25__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA26__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA27__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA28__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA29__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA30__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CRA__DOT____Vcellinp__FA31__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CSA__DOT__c8;
        CData/*0:0*/ Block_adder_total__DOT__CSA__DOT__c16;
        CData/*7:0*/ Block_adder_total__DOT__CSA__DOT__RCA_L__DOT__carry;
        CData/*0:0*/ Block_adder_total__DOT__CSA__DOT__RCA_L__DOT____Vcellout__FA1__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSA__DOT__RCA_L__DOT____Vcellout__FA2__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSA__DOT__RCA_L__DOT____Vcellout__FA3__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSA__DOT__RCA_L__DOT____Vcellout__FA4__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSA__DOT__RCA_L__DOT____Vcellout__FA5__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSA__DOT__RCA_L__DOT____Vcellout__FA6__o_c;
        CData/*7:0*/ Block_adder_total__DOT__CSA__DOT__RCA_H0__DOT__carry;
        CData/*7:0*/ Block_adder_total__DOT__CSA__DOT__RCA_H1__DOT__carry;
        CData/*7:0*/ Block_adder_total__DOT__CSA__DOT__RCA_H2_0__DOT__carry;
        CData/*7:0*/ Block_adder_total__DOT__CSA__DOT__RCA_H2_1__DOT__carry;
        CData/*7:0*/ Block_adder_total__DOT__CSA__DOT__RCA_H3_0__DOT__carry;
        CData/*7:0*/ Block_adder_total__DOT__CSA__DOT__RCA_H3_1__DOT__carry;
        CData/*7:0*/ Block_adder_total__DOT__CSKA__DOT__group_P;
        CData/*7:0*/ Block_adder_total__DOT__CSKA__DOT__group_Carry;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__0__KET____DOT__rca__DOT____Vcellout__FA0__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__0__KET____DOT__rca__DOT____Vcellout__FA1__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__0__KET____DOT__rca__DOT____Vcellout__FA2__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__1__KET____DOT__rca__DOT____Vcellout__FA0__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__1__KET____DOT__rca__DOT____Vcellout__FA1__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__1__KET____DOT__rca__DOT____Vcellout__FA2__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__2__KET____DOT__rca__DOT____Vcellout__FA0__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__2__KET____DOT__rca__DOT____Vcellout__FA1__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__2__KET____DOT__rca__DOT____Vcellout__FA2__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__3__KET____DOT__rca__DOT____Vcellout__FA0__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__3__KET____DOT__rca__DOT____Vcellout__FA1__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__3__KET____DOT__rca__DOT____Vcellout__FA2__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__4__KET____DOT__rca__DOT____Vcellout__FA0__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__4__KET____DOT__rca__DOT____Vcellout__FA1__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__4__KET____DOT__rca__DOT____Vcellout__FA2__o_c;
    };
    struct {
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__5__KET____DOT__rca__DOT____Vcellout__FA0__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__5__KET____DOT__rca__DOT____Vcellout__FA1__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__5__KET____DOT__rca__DOT____Vcellout__FA2__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__6__KET____DOT__rca__DOT____Vcellout__FA0__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__6__KET____DOT__rca__DOT____Vcellout__FA1__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__6__KET____DOT__rca__DOT____Vcellout__FA2__o_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__7__KET____DOT__rca__DOT____Vcellinp__FA1__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__7__KET____DOT__rca__DOT____Vcellinp__FA2__i_c;
        CData/*0:0*/ Block_adder_total__DOT__CSKA__DOT__CSKA_BLOCK__BRA__7__KET____DOT__rca__DOT____Vcellinp__FA3__i_c;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb5b58e20__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hdea43a30__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hdeac9ff2__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hbabea72a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha353cb0a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hbeca450a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_heec65c01__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha0169a1c__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha688435a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hbb06fc1e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hdf51c551__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hded921cd__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb6bc7a70__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h529db6ec__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hbeb089b2__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he09955a2__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf16da826__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf18013f6__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf1b2b3d9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hd2cf6755__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h5984059c__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h59971b44__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hefd74ab2__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he936b888__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb6ce19c7__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb9538ed4__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha68544d0__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha9d0c4eb__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb7f74b1a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf5a1edd5__0;
        CData/*1:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h70fb64d3__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf372fb54__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf6cb6bc5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf1b33f6f__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hcc8ca85b__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hc799c0cd__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hcba26e24__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he28b5042__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h377570d3__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0d399fb5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hcca504e2__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf1b66a1a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf6e73a66__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf0da3cdc__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0f018e7b__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h3bbf92f7__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he5d8df45__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfea5fe27__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hff4eed4a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfe728400__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfd72705e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h12a6ed9e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h131d3ba3__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he252bae5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he14356fb__0;
    };
    struct {
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h386a6bbd__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h38eef1ba__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h361ebc08__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h36e3ff88__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h35ca30f2__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfeeeef25__0;
        CData/*1:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha616c649__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4669030b__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h5ef05ee0__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hc4020dbf__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h031237c0__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h3aedc873__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h54c421a5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb57e79d6__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h571a90b7__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h77d4a7e9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h542bef1b__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h34b4b29e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6bdf61b4__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h58881925__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6ffabe31__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h270399d9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h89973fd2__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hdabf56f9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h51661bdb__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0e7538eb__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hed303474__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hc6e098df__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h361c6d67__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfe22944d__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h41d8fee4__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h7dc1c4cb__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4db0cbbb__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h475abd8e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h7ceaf14f__0;
        CData/*3:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6c69239c__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h537867a6__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h43852427__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfff31c34__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h9e535c94__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb9994404__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hc7d602b6__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hc5aadebe__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h2ac739f0__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h9f373942__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4cb699b1__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he8cec54d__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0f378dc9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4b232004__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h3426f76d__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h2b6250a0__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hcf063a16__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hec46bc1d__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h45e0afcb__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he10e6912__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha3954fdf__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h5f433d21__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h3b9a663d__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfa392fad__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha6c8ee3a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h07ddeeba__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h2b88d2f9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfd311044__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6e4f2179__0;
    };
    struct {
        CData/*3:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h1d2846ec__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h3c8ad5df__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h3d38d598__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h1ee99306__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0115502c__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hcdf34a70__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h716a8ccb__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha4d0e8d3__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h26aa0ccd__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h111e81cd__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h345a2e7c__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h973e7a0a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h2d3a81a4__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0fffa626__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h8985e572__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hd29215d0__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h16b76ce4__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h59e0ec80__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h58321c15__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h2e37be68__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h892d09ae__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hcb9df61b__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6b283d2a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h088deb9c__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h9d3f4eeb__0;
        CData/*7:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_haf8cc564__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h1a16fce0__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h32b7cfd3__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h96898b0f__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he96df775__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf4c727ff__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf641505b__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h3d8785f1__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h76396dd3__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hcd99fc2f__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h256feb86__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h5006b846__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hfe6b2bf9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf0eae794__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4097b7b5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h3606f45e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4d2de941__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h358e1b4b__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he5086fc9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb8c87dca__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h5fb0cac5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf852b517__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h49cd688b__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h026cf16a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h00e60d48__0;
        CData/*7:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h349ebd05__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h97a38d12__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h34143b46__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hac4cd6ae__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf45cb34f__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h62eef385__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he25df9c0__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hd9995e3d__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h1d9e18ca__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h46650077__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h2c147164__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h7da363f6__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0c8bee28__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hd639f895__0;
    };
    struct {
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6b68da7e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h47ccf2e8__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h1ed7b901__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6c5b1bc9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h54c3669c__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h1e093ef5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hae627dd5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hac919d47__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hdda4b4e5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hcd4da507__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h475b5e57__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4b0d9c42__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h8063b25f__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h7087b9ae__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h9da1f1fc__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hb3d6b21e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h681ff933__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hbbb27814__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0035f299__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h73bc7e8a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h46c9cd1e__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h73ba5b6f__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h64526989__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hf10a4e06__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hbc8f09e2__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hda00ae4a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4dd7a24a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h4dc3ac78__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h49aee321__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6e76d6b8__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he8f00ef4__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h19289043__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hc10a4c84__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6244a9ec__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h78fd1ea9__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_ha76b18b8__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h71d5b11f__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h476df2f1__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hdf866125__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h91dd81ba__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h96ace1fa__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h74b5da3c__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h9ed2bb3d__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0d6361d5__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h2d016e2a__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h6ce873d1__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_hc3442b04__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_he8135cde__0;
        CData/*0:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h5b1e7ec7__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_L__DOT__carry__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H1__DOT__carry__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H0__DOT__carry__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H2_1__DOT__carry__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H2_0__DOT__carry__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H3_1__DOT__carry__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H3_0__DOT__carry__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSKA__DOT__group_Carry__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_L__DOT__carry__1;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H1__DOT__carry__1;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H0__DOT__carry__1;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H2_1__DOT__carry__1;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H2_0__DOT__carry__1;
    };
    struct {
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H3_1__DOT__carry__1;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H3_0__DOT__carry__1;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSKA__DOT__group_Carry__1;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_L__DOT__carry__2;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H1__DOT__carry__2;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H0__DOT__carry__2;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H2_1__DOT__carry__2;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H2_0__DOT__carry__2;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H3_1__DOT__carry__2;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSA__DOT__RCA_H3_0__DOT__carry__2;
        CData/*7:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CSKA__DOT__group_Carry__2;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h0a69d39a__0;
        SData/*15:0*/ Block_adder_total__DOT__KSA__DOT____VdfgTmp_h1f0b425b__0;
        VL_IN(i_a,31,0);
        VL_IN(i_b,31,0);
        VL_OUT(o_CRA,31,0);
        VL_OUT(o_CLA,31,0);
        VL_OUT(o_CSA,31,0);
        VL_OUT(o_CSKA,31,0);
        VL_OUT(o_KSA,31,0);
        IData/*31:0*/ Block_adder_total__DOT__CLA__DOT__P;
        IData/*31:0*/ Block_adder_total__DOT__CLA__DOT__G;
        IData/*31:0*/ Block_adder_total__DOT__CLA__DOT__C;
        IData/*31:0*/ Block_adder_total__DOT__CSKA__DOT__c_internal;
        IData/*31:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CLA__DOT__C__0;
        IData/*31:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CLA__DOT__C__1;
        IData/*31:0*/ __Vtrigprevexpr___TOP__Block_adder_total__DOT__CLA__DOT__C__2;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*0:0*/, 18> __Vm_traceActivity;
    };
    VlTriggerVec<10> __VstlTriggered;
    VlTriggerVec<10> __VicoTriggered;
    VlTriggerVec<9> __VactTriggered;
    VlTriggerVec<9> __VnbaTriggered;

    // INTERNAL VARIABLES
    VBlock_adder_total__Syms* const vlSymsp;

    // CONSTRUCTORS
    VBlock_adder_total___024root(VBlock_adder_total__Syms* symsp, const char* v__name);
    ~VBlock_adder_total___024root();
    VL_UNCOPYABLE(VBlock_adder_total___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
